/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author mtsfs
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonEntrar = new javax.swing.JButton();
        TextUsuario = new javax.swing.JTextField();
        TextSenha = new javax.swing.JPasswordField();
        jLabelTextSenha = new javax.swing.JLabel();
        jLabelTextUsuario = new javax.swing.JLabel();
        jLabelTextLogin = new javax.swing.JLabel();
        jLabelMapleName = new javax.swing.JLabel();
        jLabelLogoPainel = new javax.swing.JLabel();
        jLabelFundoPainel = new javax.swing.JLabel();
        jLabelFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonEntrar.setBackground(new java.awt.Color(240, 69, 69));
        jButtonEntrar.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jButtonEntrar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEntrar.setText("ENTRAR");
        jButtonEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEntrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(905, 705, 110, 40));

        TextUsuario.setAlignmentX(0.0F);
        TextUsuario.setAlignmentY(0.0F);
        TextUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(TextUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 550, 200, 40));
        getContentPane().add(TextSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 640, 200, 40));

        jLabelTextSenha.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabelTextSenha.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTextSenha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTextSenha.setText("Senha");
        getContentPane().add(jLabelTextSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(717, 590, 489, 50));

        jLabelTextUsuario.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabelTextUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTextUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTextUsuario.setText("Usuário");
        getContentPane().add(jLabelTextUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(717, 490, 489, 50));

        jLabelTextLogin.setFont(new java.awt.Font("Impact", 0, 26)); // NOI18N
        jLabelTextLogin.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTextLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTextLogin.setText("Login");
        getContentPane().add(jLabelTextLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(717, 440, 489, 50));

        jLabelMapleName.setFont(new java.awt.Font("Impact", 0, 30)); // NOI18N
        jLabelMapleName.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMapleName.setText("Maple System Resources");
        getContentPane().add(jLabelMapleName, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 335, -1, 100));

        jLabelLogoPainel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelLogoPainel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelLogoPainel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/logo-sem-fundo150x150.png"))); // NOI18N
        jLabelLogoPainel.setToolTipText("");
        jLabelLogoPainel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabelLogoPainel.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(jLabelLogoPainel, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 310, 150, 150));
        jLabelLogoPainel.getAccessibleContext().setAccessibleName("");

        jLabelFundoPainel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelFundoPainel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/Icons/painel-login.png"))); // NOI18N
        getContentPane().add(jLabelFundoPainel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        jLabelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/background-login.jpg"))); // NOI18N
        getContentPane().add(jLabelFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextUsuarioActionPerformed

    private void jButtonEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEntrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEntrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField TextSenha;
    private javax.swing.JTextField TextUsuario;
    private javax.swing.JButton jButtonEntrar;
    private javax.swing.JLabel jLabelFundo;
    private javax.swing.JLabel jLabelFundoPainel;
    private javax.swing.JLabel jLabelLogoPainel;
    private javax.swing.JLabel jLabelMapleName;
    private javax.swing.JLabel jLabelTextLogin;
    private javax.swing.JLabel jLabelTextSenha;
    private javax.swing.JLabel jLabelTextUsuario;
    // End of variables declaration//GEN-END:variables
}
