/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.MainMenuController;

/**
 *
 * @author mtsfs
 */
public class MainMenu extends javax.swing.JFrame {

    private final MainMenuController controller;

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        controller = new MainMenuController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelFundo = new javax.swing.JLabel();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuLancamentos = new javax.swing.JMenu();
        jMenuItemColaborador = new javax.swing.JMenuItem();
        jMenuItemReserva = new javax.swing.JMenuItem();
        jMenuOperacoes = new javax.swing.JMenu();
        jMenuRelatorios = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/background-menu.png"))); // NOI18N
        jLabelFundo.setPreferredSize(new java.awt.Dimension(1212, 683));

        jMenuLancamentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/Icons/planning-icon-24.png"))); // NOI18N
        jMenuLancamentos.setText("Lançamentos");

        jMenuItemColaborador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/Icons/prof-icon-24.png"))); // NOI18N
        jMenuItemColaborador.setText("Colaborador");
        jMenuLancamentos.add(jMenuItemColaborador);

        jMenuItemReserva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/Icons/plus-icon-24.png"))); // NOI18N
        jMenuItemReserva.setText("Reservas");
        jMenuItemReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemReservaActionPerformed(evt);
            }
        });
        jMenuLancamentos.add(jMenuItemReserva);

        jMenuBar.add(jMenuLancamentos);

        jMenuOperacoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/Icons/setting-icon-24.png"))); // NOI18N
        jMenuOperacoes.setText("Operação");
        jMenuBar.add(jMenuOperacoes);

        jMenuRelatorios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/Icons/relatorio-icon-24.png"))); // NOI18N
        jMenuRelatorios.setText("Relatórios");
        jMenuBar.add(jMenuRelatorios);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelFundo, javax.swing.GroupLayout.DEFAULT_SIZE, 1920, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelFundo, javax.swing.GroupLayout.DEFAULT_SIZE, 1080, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemReservaActionPerformed
        // TODO add your handling code here:
        this.controller.abrirReservas();
    }//GEN-LAST:event_jMenuItemReservaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelFundo;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenuItem jMenuItemColaborador;
    private javax.swing.JMenuItem jMenuItemReserva;
    private javax.swing.JMenu jMenuLancamentos;
    private javax.swing.JMenu jMenuOperacoes;
    private javax.swing.JMenu jMenuRelatorios;
    // End of variables declaration//GEN-END:variables
}