/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.ReservaController;
import javax.swing.JTable;

/**
 *
 * @author mtsfs
 */
public class Reserva extends javax.swing.JFrame {

    private final ReservaController controller;

    /**
     * Creates new form Reserva
     */
    public Reserva() {
        initComponents();
        controller = new ReservaController(this);
        iniciar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTableReserva = new javax.swing.JTable();
        lblHora = new javax.swing.JLabel();
        lblDataEntrega = new javax.swing.JLabel();
        lblDataReserva = new javax.swing.JLabel();
        lblServico = new javax.swing.JLabel();
        lblColaborador = new javax.swing.JLabel();
        lblId1 = new javax.swing.JLabel();
        txfHora = new javax.swing.JTextField();
        txfDataEntrega = new javax.swing.JTextField();
        txfDataReserva = new javax.swing.JTextField();
        selectServico = new javax.swing.JComboBox<>();
        selectColaborador = new javax.swing.JComboBox<>();
        txfId = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTxaObservacao = new javax.swing.JTextArea();
        lblReservar = new javax.swing.JLabel();
        jLabelReservaFundo = new javax.swing.JLabel();
        jLabelFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane2.setPreferredSize(new java.awt.Dimension(450, 400));

        jTableReserva.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "COLABORADOR", "SERVIÇO", "DATA RESERVA", "DATA ENTREGA", "HORA", "OBSERVAÇÃO"
            }
        ));
        jScrollPane2.setViewportView(jTableReserva);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 620, 1250, 270));

        lblHora.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblHora.setForeground(new java.awt.Color(255, 255, 255));
        lblHora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHora.setText("Hora");
        getContentPane().add(lblHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 505, 110, 35));

        lblDataEntrega.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblDataEntrega.setForeground(new java.awt.Color(255, 255, 255));
        lblDataEntrega.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDataEntrega.setText("Data de Entrega");
        getContentPane().add(lblDataEntrega, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 460, 140, 35));

        lblDataReserva.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblDataReserva.setForeground(new java.awt.Color(255, 255, 255));
        lblDataReserva.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDataReserva.setText("Data da Reserva");
        getContentPane().add(lblDataReserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 415, 140, 35));

        lblServico.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblServico.setForeground(new java.awt.Color(255, 255, 255));
        lblServico.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblServico.setText("Serviço");
        getContentPane().add(lblServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 370, 110, 35));

        lblColaborador.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblColaborador.setForeground(new java.awt.Color(255, 255, 255));
        lblColaborador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblColaborador.setText("Colaborador");
        getContentPane().add(lblColaborador, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 325, 110, 35));

        lblId1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblId1.setForeground(new java.awt.Color(255, 255, 255));
        lblId1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblId1.setText("Id");
        getContentPane().add(lblId1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 280, 110, 35));
        getContentPane().add(txfHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 505, 320, 35));
        getContentPane().add(txfDataEntrega, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 460, 320, 35));

        txfDataReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfDataReservaActionPerformed(evt);
            }
        });
        getContentPane().add(txfDataReserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 415, 320, 35));

        selectServico.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                selectServicoItemStateChanged(evt);
            }
        });
        getContentPane().add(selectServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 370, 320, 35));

        getContentPane().add(selectColaborador, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 325, 320, 35));

        txfId.setText("0");
        txfId.setEnabled(false);
        txfId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfIdActionPerformed(evt);
            }
        });
        getContentPane().add(txfId, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 280, 320, 35));

        jButton1.setBackground(new java.awt.Color(240, 69, 69));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("RESERVAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 495, 470, 45));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(240, 85));

        jTxaObservacao.setColumns(20);
        jTxaObservacao.setRows(5);
        jTxaObservacao.setPreferredSize(new java.awt.Dimension(240, 80));
        jTxaObservacao.setRequestFocusEnabled(false);
        jScrollPane1.setViewportView(jTxaObservacao);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 280, 470, 205));

        lblReservar.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblReservar.setForeground(new java.awt.Color(255, 255, 255));
        lblReservar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblReservar.setText("Reservar");
        getContentPane().add(lblReservar, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 150, 1480, 110));

        jLabelReservaFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/Icons/reserva-painel-fundo.png"))); // NOI18N
        getContentPane().add(jLabelReservaFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, -1, -1));

        jLabelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/background-menu-clean.png"))); // NOI18N
        getContentPane().add(jLabelFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void selectServicoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_selectServicoItemStateChanged
        
    }//GEN-LAST:event_selectServicoItemStateChanged

    private void txfIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfIdActionPerformed
    }//GEN-LAST:event_txfIdActionPerformed

    private void txfDataReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfDataReservaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfDataReservaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reserva().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabelFundo;
    private javax.swing.JLabel jLabelReservaFundo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableReserva;
    private javax.swing.JTextArea jTxaObservacao;
    private javax.swing.JLabel lblColaborador;
    private javax.swing.JLabel lblDataEntrega;
    private javax.swing.JLabel lblDataReserva;
    private javax.swing.JLabel lblHora;
    private javax.swing.JLabel lblId1;
    private javax.swing.JLabel lblReservar;
    private javax.swing.JLabel lblServico;
    private javax.swing.JComboBox<String> selectColaborador;
    private javax.swing.JComboBox<String> selectServico;
    private javax.swing.JTextField txfDataEntrega;
    private javax.swing.JTextField txfDataReserva;
    private javax.swing.JTextField txfHora;
    private javax.swing.JTextField txfId;
    // End of variables declaration//GEN-END:variables

    private void iniciar() {
        this.controller.atualizaTabela();
    }

    public JTable getjTableReserva() {
        return jTableReserva;
    }

    public void setjTableReserva(JTable jTableReserva) {
        this.jTableReserva = jTableReserva;
    }
}